apiVersion: v1
kind: Service
metadata:
  name: ghdefaults
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: HTTP
  selector:
    app.kubernetes.io/name: ghdefaults
