apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ghdefaults
spec:
  parentRefs:
    - name: default
      namespace: envoy-gateway-system
  hostnames:
    - ghdefaults.liao.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ghdefaults
          port: 80
