apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ghdefaults
      spec:
        template:
          spec:
            containers:
              - name: ghdefaults
                env:
                  - name: OTEL_SERVICE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.labels['app.kubernetes.io/name']
                  - name: POD_UID
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.uid
                  - name: OTEL_RESOURCE_ATTRIBUTES
                    value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=earbug
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: http://ingest.otelcol.svc:4317
                volumeMounts:
                  - mountPath: /var/run/secrets/github
                    name: secrets
            volumes:
              - name: secrets
                secret:
                  secretName: ghdefaults

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: ghdefaults
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../base
  - httproute.k8s.yaml
  - namespace.k8s.yaml
