substitutions:
  _IMG: ghdefaults
  _REG: us.gcr.io
tags:
  - $TAG_NAME
  - $SHORT_SHA
  - $COMMIT_SHA
steps:
  - id: login
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - gcloud secrets versions access latest --secret=registries > /login/config.json
    volumes:
      - name: login
        path: /login

  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=Dockerfile
      - -d=$_REG/$PROJECT_ID/$_IMG:latest
      - -d=$_REG/$PROJECT_ID/$_IMG:$TAG_NAME
      - -d=index.docker.io/seankhliao/$_IMG:latest
      - -d=index.docker.io/seankhliao/$_IMG:$TAG_NAME
      - --reproducible
      - --single-snapshot
    volumes:
      - name: login
        path: /kaniko/.docker

  - id: deploy
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_IMG
      - --image=$_REG/$PROJECT_ID/$_IMG:$TAG_NAME
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --concurrency=80
      - --max-instances=1
      - --cpu=1
      - --memory=128Mi
      - --timeout=10s
