kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: ghdefaults
  name: ghdefaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghdefaults
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghdefaults
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 10
      containers:
        - name: ghdefaults
          image: us.gcr.io/com-seankhliao/ghdefaults:latest
          args:
            - -tls.crt=/var/secret/tls/tls.crt
            - -tls.key=/var/secret/tls/tls.key
          ports:
            - name: https
              containerPort: 8080
            - name: metric
              containerPort: 8000
          envFrom:
            - secretRef:
                name: ghdefaults
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          volumeMounts:
            - name: certs
              mountPath: /var/secret/tls
      volumes:
        - name: certs
          secret:
            secretName: ghdefaults-cert
